// 定时任务
const cron = require('node-cron');
const { alertService } = require('../services');
const { reportService } = require('../services');

// 检查超时报警（每分钟执行一次）
const setupAlertCheckTask = () => {
  cron.schedule('* * * * *', async () => {
    try {
      console.log(`[${new Date().toISOString()}] 检查超时报警...`);
      const result = await alertService.checkOverdueAlerts();
      if (result.escalatedCount > 0) {
        console.log(`已升级 ${result.escalatedCount} 个超时报警`);
      }
    } catch (error) {
      console.error('检查超时报警失败:', error);
    }
  });
  console.log('报警超时检查任务已启动（每分钟执行）');
};

// 自动生成每日报告（每天凌晨2点执行）
const setupDailyReportTask = () => {
  cron.schedule('0 2 * * *', async () => {
    try {
      console.log(`[${new Date().toISOString()}] 开始自动生成每日报告...`);
      const result = await reportService.autoGenerateDailyReports();
      console.log(`已为 ${result.generatedCount} 位患者生成每日报告`);
    } catch (error) {
      console.error('自动生成每日报告失败:', error);
    }
  });
  console.log('每日报告生成任务已启动（每天凌晨2点执行）');
};

// 启动所有定时任务
const setupAllTasks = () => {
  setupAlertCheckTask();
  setupDailyReportTask();
  console.log('所有定时任务已配置完成');
};

module.exports = {
  setupAllTasks,
  setupAlertCheckTask,
  setupDailyReportTask
};
